/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.driven.dev.calculator.gui;
import java.net.URL;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.scene.control.TextField;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import javafx.scene.text.Text;


public class App extends Application {
        private TextField display;
        private Calc calc = new Calc();
        private GridPane gridPane = new GridPane();

        public static void main(String[] args) {
            launch(args);
        }

        @Override
        public void start(Stage primaryStage) throws Exception {
            // Create the text field
            display = new TextField();
            display.getStyleClass().contains("input");
            display.setEditable(true);

            // Create the buttons
            Button button1 = new Button("1");
            Button button2 = new Button("2");
            Button button3 = new Button("3");
            Button button4 = new Button("4");
            Button button5 = new Button("5");
            Button button6 = new Button("6");
            Button button7 = new Button("7");
            Button button8 = new Button("8");
            Button button9 = new Button("9");
            Button button0 = new Button("0");
            Button buttonPlus = new Button("+");
            Button buttonMinus = new Button("-");
            Button buttonDivide = new Button("/");
            Button buttonMultiply = new Button("*");
            Button buttonSin = new Button("sin");
            Button buttonCos = new Button("cos");
            Button buttonTan = new Button("tan");
            Button buttonLog = new Button("log");
            Button buttonSqrt = new Button("sqrt");
            Button buttonMod = new Button("%");
            Button buttonPower = new Button("^");
            Button parathesis1 = new Button("(");
            Button parathesis2 = new Button(")");
            Button buttonEquals = new Button("=");


            button1.setOnAction(e -> {
                display.setText(display.getText() + "1");
            });
            button2.setOnAction(e -> {
                display.setText(display.getText() + "2");
            });
            button3.setOnAction(e -> {
                display.setText(display.getText() + "3");
            });
            button4.setOnAction(e -> {
                display.setText(display.getText() + "4");
            });
            button5.setOnAction(e -> {
                display.setText(display.getText() + "5");
            });
            button6.setOnAction(e -> {
                display.setText(display.getText() + "6");
            });
            button7.setOnAction(e -> {
                display.setText(display.getText() + "7");
            });
            button8.setOnAction(e -> {
                display.setText(display.getText() + "8");
            });
            button9.setOnAction(e -> {
                display.setText(display.getText() + "9");
            });
            button0.setOnAction(e -> {
                display.setText(display.getText() + "0");
            });
            buttonPlus.setOnAction(e -> {
                display.setText(display.getText() + " + ");
            });
            buttonMinus.setOnAction(e -> {
                display.setText(display.getText() + " - ");
            });
            buttonDivide.setOnAction(e -> {
                display.setText(display.getText() + " / ");
            });
            buttonMultiply.setOnAction(e -> {
                display.setText(display.getText() + " * ");
            });
            buttonSin.setOnAction(e -> {
                display.setText(display.getText() + "sin ");
            });
            buttonCos.setOnAction(e -> {
                display.setText(display.getText() + "cos ");
            });
            buttonTan.setOnAction(e -> {
                display.setText(display.getText() + "tan ");
            });
            buttonLog.setOnAction(e -> {
                display.setText(display.getText() + "log ");
            });
            buttonSqrt.setOnAction(e -> {
                display.setText(display.getText() + "sqrt ");
            });
            buttonMod.setOnAction(e -> {
                display.setText(display.getText() + " % ");
            });
            buttonPower.setOnAction(e -> {
                display.setText(display.getText() + " ^ ");
            });
            parathesis1.setOnAction(e -> {
                display.setText(display.getText() + "( ");
            });
            parathesis2.setOnAction(e -> {
                display.setText(display.getText() + " )");
            });
            buttonEquals.setOnAction(e -> {
                display.setText(calc.processInput(display.getText()) + "");
            });

            // Add buttons to the grid pane
            gridPane.add(button1, 0, 0);
            gridPane.add(button2, 1, 0);
            gridPane.add(button3, 2, 0);
            gridPane.add(button4, 0, 1);
            gridPane.add(button5, 1, 1);
            gridPane.add(button6, 2, 1);
            gridPane.add(button7, 0, 2);
            gridPane.add(button8, 1, 2);
            gridPane.add(button9, 2, 2);
            gridPane.add(button0, 2, 3); 
            gridPane.add(buttonPlus, 3, 0);
            gridPane.add(buttonMinus, 3, 1);
            gridPane.add(buttonDivide, 3, 2);
            gridPane.add(buttonMultiply, 3, 3);
            gridPane.add(buttonSin, 0, 4);
            gridPane.add(buttonCos, 1, 4);
            gridPane.add(buttonTan, 2, 4);
            gridPane.add(buttonLog, 3, 4);
            gridPane.add(buttonMod, 0, 3);
            gridPane.add(buttonPower, 1, 3);
            gridPane.add(parathesis1, 0, 5);
            gridPane.add(parathesis2, 1, 5);
            gridPane.add(buttonSqrt, 2, 5);
            gridPane.add(buttonEquals, 3, 5);


            // Create the main layout
            VBox vbox = new VBox();

            vbox.getChildren().addAll(display, gridPane);
            gridPane.getStyleClass().add("div");
            gridPane.getStyleClass().add("calcDisplay");

            // Create the scene
            Scene scene = new Scene(vbox, 300, 200);

            // Set the scene and show the stage
            // URL styleURL = getClass().getResource("//style.css");
		    // String stylesheet = styleURL.toExternalForm();
		    // scene.getStylesheets().add(stylesheet);
            primaryStage.setTitle("TI 84-AD edition");
            primaryStage.setScene(scene);
            primaryStage.show();
        }
    }